/***********************************************************************/
/*                                                                     */
/*  FILE        :mouse.cpp                                             */
/*  DATE        :Fri, May 22, 2009                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :SH7125                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.5).     */
/*                                                                     */
/***********************************************************************/

//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                   // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;  // Remove the comment when you use ios
extern "C" {
  void abort(void);
}
#endif

/**************************************************************************************************/
#include "lib/MainFrame.h"
void main() {
  mainFrame mouse;
  init_serial(); // Initialize serial communication devices.
  while(1) { // Continue to run the same mouse in the same mode.
    mouse.run();
  }
}
/**************************************************************************************************/

#ifdef __cplusplus
void abort(void) {}
#endif
